//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string IsDeleted { get; set; }
    }
}
