//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDetail
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DOB { get; set; }
        public int Age { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string IsDeleted { get; set; }
    }
}
